# Generated by Django 3.2.20 on 2023-08-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getting_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.IntegerField(choices=[(0, 'Accepted'), (1, 'Discussed'), (2, 'Rejected'), (2, 'Pending')], default=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='mobile_number',
            field=models.CharField(default='+44 7123 123 123', max_length=17),
            preserve_default=False,
        ),
    ]
